#!/bin/bash

##Configuration SLURM ########
##on définit le nom du job 
#SBATCH --job-name=Cutadapt

##définir la partition utiliséei
#SBATCH -p normal

##définir le nombre de  à utiliser 
#SBATCH -c 12

#SBATCH --array=1-18%2 ##index table between 0 to 19 with 4 parallele jobs
cd /scratch
rm -r boubred
mkdir -p boubred #La valeur va varier selon le nombre de JOB 
cd boubred 

mkdir -p data/
cd data

mkdir -p RS/
cd RS

scp nas3:/data3/projects/integration/rnaseq_riz/Seq_Data/RSbis/RS*fastq.gz . 
cd ../
mkdir -p RC/
cd RC
scp nas3:/data3/projects/integration/rnaseq_riz/Seq_Data/RCbis/RC*.fastq.gz .
cd ../

echo -e "\n#----------------------------------------------#\n"
echo -e "\n################# DOWNLOAD DATA ################\n"
echo -e "\n#----------------------------------------------#\n"

##Charger les logiciel à utiliser 

module load bioinfo/FastQC/0.11.9 
module load bioinfo/multiqc/1.9 
module load bioinfo/cutadapt/3.1
module load bioinfo/seqkit/2.1.0 

## lancer l'analyse 

###

###

if [ ${SLURM_ARRAY_TASK_ID} -lt 9 -o ${SLURM_ARRAY_TASK_ID} -eq 9 ]
    then
    cd RC/
    sample_list=$(ls -1 RC*_1.fastq.gz | sed -n ${SLURM_ARRAY_TASK_ID}p)

    for R1 in ${sample_list[*]};do

        #R1=$(echo s_RS2_1.fq.gz)
        R2=$(echo $R1 | sed  "s/_1/_2/g")
        out=$(echo $R1 | sed  "s/.fastq.gz//g")
        out=$(echo $out | sed "s/_1//g")

        echo $R1
        echo $R2
        echo $out

        seqkit stats ${R1} ${R2}

        fastqc --threads 12 ${R1}
        fastqc --threads 12 ${R2}

        cutadapt -j 12 -q 30,30 -m 35 -O 7 \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGCGCTAGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGATATCGACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACGCAGACGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATATGAGTACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTGTAGACCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGGTGCGTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGAACATACCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACATAGCGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTGCGATACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACCAACAGACACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATTGGTGAGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACGCGGTTCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATATAACCTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAAGGATGACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGAAGCAGCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCGTGACCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTACAGTTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATATTCACCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCGCCTGTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACTCTATGCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTCTCGCACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAAGACGTCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGAGTACTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACCGGCCACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTTAATTGCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAACCGCGGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGTTATAACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACCAAGTCCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATTGGACTTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACAGTGGATCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATGACAAGCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTAGCTTGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCGATCCACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACCTGAACTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATTCAGGTCCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGTAGAGACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGACGAGAGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGACTTGGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGAGTCCAACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTTAAGCCCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCCGGATTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTGTATTACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCACGCCGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACTTACATCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTCCGTGCCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAAGGTACCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGAACGTTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAATTCTGCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGCCTCATCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATCTTAGTCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCTCCGACCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATACCAAGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCGTTGGACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTTCACGGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCCTGTAACACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGAATGCCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGAGGCATTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACCTCGGTACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATTCTAACGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATGAGGCTCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCAGAATCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACACTACGACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATGTCGTAGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACCACTTACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTTGTCCGCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATCCATATCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCTTGCGCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGTATCTTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGACGCTCCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACATGCCATCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATGCATTGCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATTGGAACCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCCAAGGTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACGAGATATCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATAGAGCGCCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAACCTGTTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGTTCACCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACATTGTTGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATGCCACCACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTCTGCCTCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCTCATTCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACGCCGCACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTATTATGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGATAGATCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGCGAGCTCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACAGTTCCGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATGACCTTACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTAGGCAACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCGAATGGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTTAGTGTCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCCGACACCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAACAGGAACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGTGAAGGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACCTGTGGCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATTCACAATCACATCTAGAGCCACCAGCGGCATAGTAA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGATTGTGAATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCCACAGGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCCTTCACCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTTCCTGTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTGTCGGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGACACTAAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCCATTCGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTTGCCTAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTAAGGTCATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGGAACTGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGCTCGCTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGATCTATCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCATAATACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTGCGGCGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGAATGAGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGGCAGAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTGGTGGCATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCAACAATGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGTGAACCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAACAGGTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCGCTCTATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGATATCTCGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGACCTTGGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTTCCAATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCAATGCATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGATGGCATGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGAGCGTCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAAGATACTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCGCAAGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGATATGGATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGGACAACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTAAGTGGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTACGACATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCGTAGTGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGATTCTGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGCCTCATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGTTAGAATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTACCGAGGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAATGCCTCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGCATTCTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGTTACAGGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCCGTGAAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCCAACGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTTGGTATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTCGGAGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGACTAAGATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGATGAGGCCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCAGAATTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAACGTTCCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGTACCTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCACGGACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGATGTAAGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGGCGTGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTAATACAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAATCCGGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGCTTAAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTTGGACTCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCCAAGTCTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTCTCGTCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCTCTACTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGGACCTGAATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGTTCAGGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTGGATCGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCAAGCTAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCTTGTCATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGATCCACTGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAAGTCCAATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGACTTGGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTTATAACCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCCGCGGTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGCAATTAACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTGGCCGGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGTACTCCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGACGTCTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTGCGAGACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGCATAGAGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGACAGGCGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTGAATATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAACTGTAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGTCACGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTGCTTCCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCATCCTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGGTTATATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGAACCGCGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTCACCAATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCTGTTGGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTATCGCACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGCTATGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTATGTTCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGACGCACCTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTCTACACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTACTCATATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGTCTGCGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCGATATCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTAGCGCTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -o ${out}cutadapt1.fq.gz -p ${out}cutadapt2.fq.gz ${R1} ${R2}


        seqkit stats ${out}cutadapt1.fq.gz ${out}cutadapt2.fq.gz

        fastqc --threads 12 ${out}cutadapt1.fq.gz
        fastqc --threads 12 ${out}cutadapt2.fq.gz

        scp *cutadapt* nas3:/data3/projects/integration/rnaseq_riz/output/clean/RC/
    done
    cd ../
fi    

if [ ${SLURM_ARRAY_TASK_ID} -gt 10 -o ${SLURM_ARRAY_TASK_ID} -eq 10 ]
    then
    echo TEST Condition
    cd RS/
    number=$((${SLURM_ARRAY_TASK_ID} - 9))
    sample_list=$(ls -1 RS*_1.fastq.gz | sed -n ${number}p)
    echo $sample_list
    for R1 in ${sample_list[*]};do

        #R1=$(echo s_RS2_1.fq.gz)
        R2=$(echo $R1 | sed  "s/_1/_2/g")
        out=$(echo $R1 | sed  "s/.fastq.gz//g")
        out=$(echo $out | sed "s/_1//g")

        echo $R1
        echo $R2
        echo $out

        seqkit stats ${R1} ${R2}

        fastqc --threads 12 ${R1}
        fastqc --threads 12 ${R2}

        cutadapt -j 12 -q 30,30 -m 35 -O 7 \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGCGCTAGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGATATCGACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACGCAGACGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATATGAGTACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTGTAGACCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGGTGCGTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGAACATACCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACATAGCGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTGCGATACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACCAACAGACACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATTGGTGAGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACGCGGTTCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATATAACCTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAAGGATGACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGAAGCAGCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCGTGACCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTACAGTTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATATTCACCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCGCCTGTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACTCTATGCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTCTCGCACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAAGACGTCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGAGTACTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACCGGCCACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTTAATTGCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAACCGCGGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGTTATAACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACCAAGTCCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATTGGACTTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACAGTGGATCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATGACAAGCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTAGCTTGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCGATCCACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACCTGAACTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATTCAGGTCCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGTAGAGACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGACGAGAGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGACTTGGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGAGTCCAACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTTAAGCCCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCCGGATTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTGTATTACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCACGCCGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACTTACATCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTCCGTGCCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAAGGTACCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGAACGTTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAATTCTGCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGCCTCATCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATCTTAGTCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCTCCGACCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATACCAAGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCGTTGGACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTTCACGGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCCTGTAACACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGAATGCCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGAGGCATTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACCTCGGTACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATTCTAACGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATGAGGCTCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCAGAATCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACACTACGACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATGTCGTAGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACCACTTACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTTGTCCGCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATCCATATCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCTTGCGCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGTATCTTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGACGCTCCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACATGCCATCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATGCATTGCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAATTGGAACCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGCCAAGGTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACGAGATATCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATAGAGCGCCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAACCTGTTCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGTTCACCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACATTGTTGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATGCCACCACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTCTGCCTCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCTCATTCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAACGCCGCACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGTATTATGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGATAGATCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAGCGAGCTCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACAGTTCCGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATGACCTTACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTAGGCAACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCGAATGGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACTTAGTGTCACATCTAGAGCCACCAGCGGCATAGTAA \
        -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATCCGACACCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAAACAGGAACACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACAGGTGAAGGCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACACCTGTGGCCACATCTAGAGCCACCAGCGGCATAGTAA -b TCTAGCCTTCTCGCAGCACATCCCTTTCTCACATTCACAATCACATCTAGAGCCACCAGCGGCATAGTAA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGATTGTGAATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCCACAGGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCCTTCACCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTTCCTGTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTGTCGGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGACACTAAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCCATTCGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTTGCCTAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTAAGGTCATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGGAACTGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGCTCGCTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGATCTATCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCATAATACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTGCGGCGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGAATGAGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGGCAGAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTGGTGGCATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCAACAATGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGTGAACCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAACAGGTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCGCTCTATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGATATCTCGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGACCTTGGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTTCCAATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCAATGCATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGATGGCATGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGAGCGTCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAAGATACTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCGCAAGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGATATGGATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGGACAACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTAAGTGGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTACGACATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCGTAGTGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGATTCTGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGCCTCATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGTTAGAATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTACCGAGGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAATGCCTCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGCATTCTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGTTACAGGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCCGTGAAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCCAACGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTTGGTATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTCGGAGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGACTAAGATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGATGAGGCCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCAGAATTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAACGTTCCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGTACCTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCACGGACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGATGTAAGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGGCGTGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTAATACAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAATCCGGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGCTTAAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTTGGACTCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCCAAGTCTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTCTCGTCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCTCTACTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGGACCTGAATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGTTCAGGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTGGATCGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCAAGCTAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGCTTGTCATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGATCCACTGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAAGTCCAATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGACTTGGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTTATAACCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCCGCGGTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGCAATTAACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTGGCCGGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGTACTCCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGACGTCTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTGCGAGACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGCATAGAGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGACAGGCGCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTGAATATTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAACTGTAGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGGTCACGATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTGCTTCCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCATCCTTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGAGGTTATATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGAACCGCGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTCACCAATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCTGTTGGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTATCGCACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGCTATGTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTATGTTCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGACGCACCTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -B TTACTATGCCGCTGGTGGCTCTAGATGTGGTCTACACTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTACTCATATGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCGTCTGCGTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGTCGATATCTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA -B TTACTATGCCGCTGGTGGCTCTAGATGTGCTAGCGCTTGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGA \
        -o ${out}cutadapt1.fq.gz -p ${out}cutadapt2.fq.gz ${R1} ${R2}

        seqkit stats ${out}cutadapt1.fq.gz ${out}cutadapt2.fq.gz

        fastqc --threads 12 ${out}cutadapt1.fq.gz
        fastqc --threads 12 ${out}cutadapt2.fq.gz
        
        scp *cutadapt* nas3:/data3/projects/integration/rnaseq_riz/output/clean/RS/
        
    done
    cd ../
fi    
if [ ${SLURM_ARRAY_TASK_ID} -eq 18 ]
    then
    
    multiqc .
    scp -r * nas3:/data3/projects/integration/rnaseq_riz/output/clean/
    cd ../
    rm -rf /scratch/boubred
    echo -e "\n#----------------------------------------------#\n"
    echo -e "\n################# Suppr /scratch ################\n"
    echo -e "\n#----------------------------------------------#\n"
fi 
